CREATE TABLE `comm_icd10` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`ICD_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`ICD_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HELP_CODE` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`TYPE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKCOMM_ICD10` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `comm_icd10_type` (
`TYPE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`TYPE_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKCOMM_ICD10_TYPE` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_bil_cl_receipt` (
`CL_RECEIPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`CL_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`CASHIER` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`RECEICPT_CODE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`RECIVER_TIME` date NOT NULL,
`CASH_AMT` float(10,2) NOT NULL,
`CARD_AMT` float(10,2) NOT NULL,
`INSURANCE_AMT` float(10,2) NULL DEFAULT NULL,
`SUM_AMT` float(10,2) NULL DEFAULT NULL,
`REFUND_RECP_CODE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`REFUND_DATE` date NULL DEFAULT NULL,
`REFUND_OPT` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`REDUCE_AMT` int(11) NULL DEFAULT NULL,
`REDUCE_DATE` date NULL DEFAULT NULL,
`REDUCE_OPT` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`REDUCE_REASON` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`OPT_USER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_DATE` date NOT NULL,
`OPT_TERM` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_ORGA` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`CL_RECEIPT_CODE`, `CL_CODE`) ,
UNIQUE INDEX `XPKHIS_BIL_CL_RECEIPT` (`CL_RECEIPT_CODE`, `CL_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_bil_cl_recp_detail` (
`ID` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`CL_RECEIPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`CL_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_USER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_DATE` date NOT NULL,
`OPT_TERM` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_ORGA` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`FEEITEM_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`FEEITEM_NAME` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`PRICE` float(10,4) NOT NULL,
`COUNT` float(10,2) NULL DEFAULT NULL,
`UNIT` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`AMT` float(10,2) NULL DEFAULT NULL,
PRIMARY KEY (`ID`, `CL_RECEIPT_CODE`, `CL_CODE`) ,
UNIQUE INDEX `XPKHIS_BIL_CL_RECP_DETAIL` (`ID`, `CL_RECEIPT_CODE`, `CL_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_bil_counter` (
`ID` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`CASHIER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`START_IVNNO` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`END_IVNNO` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`RECP_TYPE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`USE_TYPE` varchar(2) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`RECP_COUNT` float(5,0) NOT NULL,
`PRE_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`REFOUNDED_COUNT` float(5,0) NOT NULL,
`INVALID_COUNT` float(5,0) NOT NULL,
`OPT_USER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_DATE` date NOT NULL,
`OPT_TERM` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_ORGA` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_BIL_COUNTER` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_cl_daily_statement` (
`ID` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPERATOR` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`OPERATE_TIME` date NULL DEFAULT NULL,
`RECIVER` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`START_TIME` date NULL DEFAULT NULL,
`END_TIME` date NULL DEFAULT NULL,
`START_RECEIPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`END_RECEIPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`RECEIPT__NUM` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`RETUEN_RECEIPT_NUM` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_CL_DAILY_STATEMENT` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_cl_daily_statement_itemtyp` (
`ID` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`DAILY_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`ITEM_TYPE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ITEM_SUM_PAY` int(11) NULL DEFAULT NULL,
`ITEM_CASH_PAY` int(11) NULL DEFAULT NULL,
`ITEM_CARD_PAY` int(11) NULL DEFAULT NULL,
`ITEM_INSURANCE_PAY` int(11) NULL DEFAULT NULL,
`STATUS` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`, `DAILY_CODE`) ,
UNIQUE INDEX `XPKHIS_CL_DAILY_STATEMENT_ITEM` (`ID`, `DAILY_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_cl_medical_record` (
`CL_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`PHA_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`DOCTOR_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`CL_DATE` date NULL DEFAULT NULL,
`IP` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ICD_CODE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ICD_NAME` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`MEMO` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`OPT_USER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_DATE` date NOT NULL,
`OPT_TERM` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_ORGA` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`CL_CODE`) ,
UNIQUE INDEX `XPKHIS_CL_MEDICAL_RECORD` (`CL_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_cl_order_item` (
`ID` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`CL_PRES_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`CL_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`ITEM_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ITEM_NAME` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`COUNT` float(10,4) NULL DEFAULT NULL,
`PRICE` float(10,4) NULL DEFAULT NULL,
`ITEM_TYPE` varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`SPEC` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`UNIT` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`SUM_AMT` float(10,2) NULL DEFAULT NULL,
`STATUS` varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`HERB_NUM` float(10,4) NULL DEFAULT NULL,
`OPT_USER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_DATE` date NOT NULL,
`OPT_TERM` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_ORGA` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`ID`, `CL_PRES_CODE`, `CL_CODE`) ,
UNIQUE INDEX `XPKHIS_CL_ORDER_ITEM` (`ID`, `CL_PRES_CODE`, `CL_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_cl_prescription` (
`CL_PRES_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`CL_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`STATUS` varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`APPLY_DEPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`DOCTOR_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`OPERATE_DEPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`SUM_AMT` float(10,2) NULL DEFAULT NULL,
`OPT_USER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_DATE` date NOT NULL,
`OPT_TERM` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_ORGA` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`CL_PRES_CODE`, `CL_CODE`) ,
UNIQUE INDEX `XPKHIS_CL_PRESCRIPTION` (`CL_PRES_CODE`, `CL_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_cl_pres_detail_cancle` (
`ID` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`CL_PRES_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`CL_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`STATUS` varchar(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`APPLY_DEPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`DOCTOR_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`OPERATE_DEPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`SUM_AMT` float(10,2) NULL DEFAULT NULL,
`OPT_USER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_DATE` date NOT NULL,
`OPT_TERM` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_ORGA` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`ID`, `CL_PRES_CODE`, `CL_CODE`) ,
UNIQUE INDEX `XPKHIS_CL_PRES_DETAIL_CANCLE` (`ID`, `CL_PRES_CODE`, `CL_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_account` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`ACCOUNT` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`PASSWORD` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`ROLE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`USER_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`ADMIN_TYPE` varchar(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`IS_USE` varchar(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`AUTHORITY_XML` varchar(4000) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`LAST_LOGINTIME` date NULL DEFAULT NULL,
`HOSPITAL_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_dept` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`DEPT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DEPT_NAME` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HELP_CODE` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DEPT_TYPE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HOSPITAL_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_COMM_DEPT` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_dict_info` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`TYPE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DICT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DICT_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HELP_CODE` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_COMM_DICT_` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_dict_type` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`TYPE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`TYPE_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HELP_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_COMM_DICT_TYPE` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_doctor` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DOCTOR_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DOCTOR_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DEPT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HISPITAL_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DOCTOR_SEX` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DOCTOR_TEL` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DOCTOR_NATION` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MERRIAGE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DOCTOR_EMAIL` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DOCTOR_TITLE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DOCTOR_TITLEGRADE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HELP_CODE` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`REMARK` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_dosage` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`DOSAGE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DOSAGE_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HELP_CODE` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_COMM_` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_efficacy` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`EFFICACY_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`EFFICACY_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HELP_CODE` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_COMM_` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_feeitem` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`FEEITEM_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`FEEITEM_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HELP_CODE` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`FEEITEM_TYPE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_COMM_` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_function` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`MODULE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`FUNCTION_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`FUNCTION_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`IS_USE` varchar(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HOSPITAL_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`REMARKS` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_COMM_FUNCTION` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_hospital` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`HOSPITAL_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HOSPITAL_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HOSPITAL_LEVEL` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HELP_CODE` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_COMM_HOSPITAL` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_manufacture` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`MANUFACTURE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`MANUFACTURE_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`LOCALITY_TYPE` varchar(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREDIT_CODE` int(11) NULL DEFAULT NULL,
`MANUFACTURE_ADDRESS` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`LINK_MAN` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`LINK_TEL` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`LINK_EMAIL` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`FAX` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`APTITUDE` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`APTITUDE_DATE` date NULL DEFAULT NULL,
`HELP_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HOSPITAL_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_COMM_` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_medinfo` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`MED_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HELP_CODE` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MENUFACTURE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_SPC` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_UNIT` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DOSAGE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`APPROVAL_NUMBER` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`EFFICACY_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`ORIGIN` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`MEDINFO_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`PAKAGE_UNIT` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`PAKAGE_PM_NUMBER` int(11) NULL DEFAULT NULL,
`DEFAULT_DOSAGE_AMOUNT` decimal(12,4) NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_COMM_MEDINFO` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_medname` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`MED_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`TYPE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HELP_CODE` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_COMM_MEDNAME` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_medtype` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`TYPE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`TYPE_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HELP_CODE` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_COMM_MEDTYPE` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_module` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`MODULE_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MODULE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`SYSTEM_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`IS_USE` varchar(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HOSPITAL_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`REMARK` char(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_COMM_MODLE` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_role` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`ROLE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`ROLE_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`ROLE_XML` varchar(4000) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HOSPITAL_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`IS_USE` varchar(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKCOMM_DICT` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_comm_system` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`SYSTEM_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`SYSTEM_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`IS_USER` varchar(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HOSPITAL_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_COMM_SYSTEM` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_ds_changeprice` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MEMO` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CHANGE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_DS_CHANGEPRICE` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_ds_changepriceinfo` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`MEDINFO_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_SPC` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`VALIDITY_DATE` date NULL DEFAULT NULL,
`MED_PRICE` decimal(12,4) NULL DEFAULT NULL,
`PURCHASE_PRICE` decimal(12,4) NULL DEFAULT NULL,
`WHOLESALE_PRICE` decimal(12,4) NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`PAKAGE_UNIT` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_MADETIME` date NULL DEFAULT NULL,
`BATCHNO` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`NEW_PRICE` decimal(12,4) NULL DEFAULT NULL,
`CHANGE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_DS_CHANGEPRICEINFO` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_ds_export` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`EXPORT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MANUFACTURE_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MANUFACTURE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`EXPORT_TYPE` varchar(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`EXPORT_DEPT` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`COST` decimal(12,4) NULL DEFAULT NULL,
`OPERATOR_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`OPERATOR_DATE` date NULL DEFAULT NULL,
`CANCEL_OPERATOR` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CANCEL_DATE` date NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_DS_EXPORT` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_ds_exportinfo` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`EXPORT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MEDINFO_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_NAME` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`PAKAGE_UNIT` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`PAKAGE_AMOUNT` decimal(12,4) NULL DEFAULT NULL,
`MED_PRICE` decimal(12,4) NULL DEFAULT NULL,
`PURCHASE_PRICE` decimal(12,4) NULL DEFAULT NULL,
`VALIDITY_DATE` date NULL DEFAULT NULL,
`BATCHNO` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_MADETIME` date NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_DS_EXPORTINFO` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_ds_import` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`IMPORT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`IMPORT_TYPE` varchar(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MANUFACTURE_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MANUFACTURE_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`INVOICE_NO` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`ACCOUNT_FLAG` varchar(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`ACCOUNT_DATE` date NULL DEFAULT NULL,
`ISPAY_FLAG` varchar(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`PAY_TIME` date NULL DEFAULT NULL,
`CONTRACT_NO` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`IMPORT_FLAG` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`COST` decimal(12,4) NULL DEFAULT NULL,
`CREATE_BY` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`PURCHASER` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`PURCHASE_DATE` date NULL DEFAULT NULL,
`CANCEL_OPRATOR` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CANCEL_DATE` date NULL DEFAULT NULL,
`HOSPITAL_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_DS_IMPORT` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_ds_importinfo` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`IMPORT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`PAKAGE_UNIT` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`PAKAGE_AMOUNT` int(11) NULL DEFAULT NULL,
`MENUFACTURE_CODE` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MEDINFO_CODE` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_SPC` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_PRICE` decimal(12,4) NULL DEFAULT NULL,
`PURCHASE_PRICE` decimal(12,4) NULL DEFAULT NULL,
`VALIDITY_DATE` date NULL DEFAULT NULL,
`BATCHNO` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_MADETIME` date NULL DEFAULT NULL,
`WHOLESALE_PRICE` decimal(12,4) NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_DS_IMPORTINFO` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_ds_stock` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`MEDINFO_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_SPC` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`VALIDITY_DATE` date NULL DEFAULT NULL,
`MED_PRICE` decimal(12,4) NULL DEFAULT NULL,
`PURCHASE_PRICE` decimal(12,4) NULL DEFAULT NULL,
`WHOLESALE_PRICE` decimal(12,4) NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`PAKAGE_UNIT` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_MADETIME` date NULL DEFAULT NULL,
`BATCHNO` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`PAKAGE_AMOUNT` decimal(12,4) NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_DS_STOCK` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_hos_account` (
`HOS_ACC_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`HIS_HOS_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`IP` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`SUM_IN` float(10,2) NOT NULL,
`SUM_OUT` float(10,2) NOT NULL,
`ACCOUNT_BALANCE` float(10,2) NULL DEFAULT NULL,
`LOWER_LIMIT` float(10,2) NULL DEFAULT NULL,
`OPT_USER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_DATE` date NOT NULL,
`OPT_TERM` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_ORGA` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`HOS_ACC_CODE`, `HIS_HOS_CODE`) ,
UNIQUE INDEX `XPKHIS_HOS_ACCOUNT` (`HOS_ACC_CODE`, `HIS_HOS_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_hos_account_log` (
`ID` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`HOS_ACC_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`HIS_HOS_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`AMT` float(12,2) NULL DEFAULT NULL,
`PAY_TYPE` varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`IS_REFUND` varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`OPT_USER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_DATE` date NOT NULL,
`OPT_TERM` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_ORGA` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`ID`, `HOS_ACC_CODE`, `HIS_HOS_CODE`) ,
UNIQUE INDEX `XPKHIS_HOS_ACCOUNT_LOG` (`ID`, `HOS_ACC_CODE`, `HIS_HOS_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_hos_daily_statement` (
`OPERATOR` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`OPERATE_TIME` date NULL DEFAULT NULL,
`RECIVER` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`START_TIME` date NULL DEFAULT NULL,
`END_TIME` date NULL DEFAULT NULL,
`START_RECEIPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`END_RECEIPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`RECEIPT__NUM` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`RETUEN_RECEIPT_NUM` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ID` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_HOS_DAILY_STATEMENT` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_hos_daily_statement_itemty` (
`ID` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`ITEM_TYPE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ITEM_SUM_PAY` int(11) NULL DEFAULT NULL,
`ITEM_CASH_PAY` int(11) NULL DEFAULT NULL,
`ITEM_CARD_PAY` int(11) NULL DEFAULT NULL,
`ITEM_INSURANCE_PAY` int(11) NULL DEFAULT NULL,
`STATUS` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`DAILY_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`ID`, `DAILY_CODE`) ,
UNIQUE INDEX `XPKHIS_HOS_DAILY_STATEMENT_ITE` (`ID`, `DAILY_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_hos_medical_record` (
`IP` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`HIS_HOS_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`Case_Code` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`Patient_Name` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`MD_Dept_ID` float NULL DEFAULT NULL,
`MD_SickRoom_ID` float NULL DEFAULT NULL,
`ME_Bed_ID` float NULL DEFAULT NULL,
`In_Date` date NULL DEFAULT NULL,
`Out_Date` date NULL DEFAULT NULL,
`Status` float NULL DEFAULT NULL,
`In_Hospital_Order` float NULL DEFAULT NULL,
`Create_by` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`Update_date` date NULL DEFAULT NULL,
`Update_by` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`is_removed` float NULL DEFAULT NULL,
`Help_Code` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`Create_date` date NULL DEFAULT NULL,
`Charge_Doctor_Name` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`Charge_Nurse_ID` float NULL DEFAULT NULL,
`Charge_Nurse_Name` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`Patient_Pay_Type` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`NURSING_CLASS` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`PATIENT_CONDITION` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ACCL_ACCT_ID` int(11) NULL DEFAULT NULL,
`TYPE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`CHANGE_DEPT_HELP` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`IN_WAY` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`IN_WAY_Doctor` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`IS_INFECTION` float NULL DEFAULT NULL,
`INTRODUCER` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ATTENDING_DOCTOR_ID` int(11) NULL DEFAULT NULL,
`IN_HOS_AGE` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`MD_DEPT_NAME` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`MD_BED_CODE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`MD_SICKROOM_NAME` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`DOC_EDIT_IS` int(11) NULL DEFAULT NULL,
`DOC_EDIT_Account` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`Nurse_EDIT_IS` int(11) NULL DEFAULT NULL,
`Nurse_EDITAccount` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
PRIMARY KEY (`HIS_HOS_CODE`) ,
UNIQUE INDEX `XPKHIS_HOS_MEDICAL_RECORD` (`HIS_HOS_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_hos_monthly_statement` (
`OPERATOR` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`OPERATE_TIME` date NULL DEFAULT NULL,
`RECIVER` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`START_TIME` date NULL DEFAULT NULL,
`END_TIME` date NULL DEFAULT NULL,
`START_RECEIPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`END_RECEIPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`RECEIPT__NUM` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`RETUEN_RECEIPT_NUM` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ID` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_HOS_MONTHLY_STATEMENT` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_hos_monthly_statement_item` (
`ITEM_TYPE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ITEM_SUM_PAY` int(11) NULL DEFAULT NULL,
`ITEM_CASH_PAY` int(11) NULL DEFAULT NULL,
`ITEM_CARD_PAY` int(11) NULL DEFAULT NULL,
`ITEM_INSURANCE_PAY` int(11) NULL DEFAULT NULL,
`STATUS` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ID` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`MONTHLY_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`ID`, `MONTHLY_CODE`) ,
UNIQUE INDEX `XPKHIS_HOS_MONTHLY_STATEMENT_I` (`ID`, `MONTHLY_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_hos_order_item` (
`ID` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`HOS_PRES_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`HIS_HOS_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`ITEM_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ITEM_NAME` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`COUNT` float(10,4) NULL DEFAULT NULL,
`PRICE` float(10,4) NULL DEFAULT NULL,
`ITEM_TYPE` varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`SPEC` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`UNIT` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`SUM_AMT` float(10,2) NULL DEFAULT NULL,
`STATUS` varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`HERB_NUM` float(10,4) NULL DEFAULT NULL,
`OPT_USER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_DATE` date NOT NULL,
`OPT_TERM` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_ORGA` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`ID`, `HOS_PRES_CODE`, `HIS_HOS_CODE`) ,
UNIQUE INDEX `XPKHIS_HOS_ORDER_ITEM` (`ID`, `HOS_PRES_CODE`, `HIS_HOS_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_hos_prescription` (
`HOS_PRES_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`HIS_HOS_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`STATUS` varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`APPLY_DEPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`DOCTOR_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`OPERATE_DEPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`SUM_AMT` float(10,2) NULL DEFAULT NULL,
`OPT_USER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_DATE` date NOT NULL,
`OPT_TERM` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_ORGA` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`HOS_PRES_CODE`, `HIS_HOS_CODE`) ,
UNIQUE INDEX `XPKHIS_HOS_PRESCRIPTION` (`HOS_PRES_CODE`, `HIS_HOS_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_hos_pres_detail_cancle` (
`ID` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`STATUS` varchar(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`APPLY_DEPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`DOCTOR_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`OPERATE_DEPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`SUM_AMT` float(10,2) NULL DEFAULT NULL,
`OPT_USER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_DATE` date NOT NULL,
`OPT_TERM` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_ORGA` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`HOS_PRES_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`HIS_HOS_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`ID`, `HOS_PRES_CODE`, `HIS_HOS_CODE`) ,
UNIQUE INDEX `XPKHIS_HOS_PRES_DETAIL_CANCLE` (`ID`, `HOS_PRES_CODE`, `HIS_HOS_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_hos_receipt` (
`HOS_RECEIPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`HIS_HOS_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`CASHIER` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`RECEICPT_CODE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`RECIVER_TIME` date NOT NULL,
`CASH_AMT` float(10,2) NOT NULL,
`CARD_AMT` float(10,2) NOT NULL,
`INSURANCE_AMT` float(10,2) NULL DEFAULT NULL,
`SUM_AMT` float(10,2) NULL DEFAULT NULL,
`REDUCE_AMT` int(11) NULL DEFAULT NULL,
`REDUCE_DATE` date NULL DEFAULT NULL,
`REDUCE_OPT` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`REDUCE_REASON` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`OPT_USER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_DATE` date NOT NULL,
`OPT_TERM` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_ORGA` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`HOS_RECEIPT_CODE`, `HIS_HOS_CODE`) ,
UNIQUE INDEX `XPKHIS_HOS_RECEIPT` (`HOS_RECEIPT_CODE`, `HIS_HOS_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_hos_receipt_cancle` (
`HOS_RECEIPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`HIS_HOS_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`CASHIER` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`RECEICPT_CODE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`RECIVER_TIME` date NOT NULL,
`CASH_AMT` float(10,2) NOT NULL,
`CARD_AMT` float(10,2) NOT NULL,
`INSURANCE_AMT` float(10,2) NULL DEFAULT NULL,
`SUM_AMT` float(10,2) NULL DEFAULT NULL,
`REDUCE_AMT` int(11) NULL DEFAULT NULL,
`REDUCE_DATE` date NULL DEFAULT NULL,
`REDUCE_OPT` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`REDUCE_REASON` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`OPT_USER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_DATE` date NOT NULL,
`OPT_TERM` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_ORGA` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`HOS_RECEIPT_CODE`, `HIS_HOS_CODE`) ,
UNIQUE INDEX `XPKHIS_HOS_RECEIPT_CANCLE` (`HOS_RECEIPT_CODE`, `HIS_HOS_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_hos_receipt_detail` (
`ID` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`HOS_RECEIPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`HIS_HOS_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`FEEITEM_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`FEEITEM_NAME` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`PRICE` float(10,4) NOT NULL,
`COUNT` float(10,2) NULL DEFAULT NULL,
`UNIT` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`AMT` float(10,2) NULL DEFAULT NULL,
`OPT_USER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_DATE` date NOT NULL,
`OPT_TERM` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_ORGA` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`ID`, `HOS_RECEIPT_CODE`, `HIS_HOS_CODE`) ,
UNIQUE INDEX `XPKHIS_HOS_RECEIPT_DETAIL` (`ID`, `HOS_RECEIPT_CODE`, `HIS_HOS_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_hos_receipt_detail_cancle` (
`ID` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`HOS_RECEIPT_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`HIS_HOS_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`FEEITEM_CODE` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`FEEITEM_NAME` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`PRICE` float(10,4) NOT NULL,
`COUNT` float(10,2) NULL DEFAULT NULL,
`UNIT` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`AMT` float(10,2) NULL DEFAULT NULL,
`OPT_USER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_DATE` date NOT NULL,
`OPT_TERM` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OPT_ORGA` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`ID`, `HOS_RECEIPT_CODE`, `HIS_HOS_CODE`) ,
UNIQUE INDEX `XPKHIS_HOS_RECEIPT_DETAIL_CANC` (`ID`, `HOS_RECEIPT_CODE`, `HIS_HOS_CODE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_pm_check` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`CHECK_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`DEPT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DEPT_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MEMO` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`LOSE_COST` decimal(12,4) NULL DEFAULT NULL,
`PROFIT_COST` decimal(12,4) NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_PM_CHECK` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_pm_checkinfo` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`MEDINFO_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_SPC` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_UNIT` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_AMOUNT` decimal(12,4) NULL DEFAULT NULL,
`REAL_AMOUNT` decimal(12,4) NULL DEFAULT NULL,
`MED_PRICE` decimal(12,4) NULL DEFAULT NULL,
`PURCHASE_PRICE` decimal(12,4) NULL DEFAULT NULL,
`WHOLESALE_PRICE` decimal(12,4) NULL DEFAULT NULL,
`VALIDITY_DATE` date NULL DEFAULT NULL,
`MED_MADETIME` date NULL DEFAULT NULL,
`BACHNO` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DEPT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_PM_CHECKINFO` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_pm_export` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`EXPORT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`RECEIVE_DEPT_CODE` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`SEND_DEPT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`HOSPITAL_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_PM_EXPORT` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_pm_exportinfo` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`EXPORT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MEDINFO_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_SPC` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_UNIT` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_AMOUNT` decimal(12,4) NULL DEFAULT NULL,
`MED_PRICE` decimal(12,4) NULL DEFAULT NULL,
`PURCHASE_PRICE` decimal(12,4) NULL DEFAULT NULL,
`WHOLESALE_PRICE` decimal(12,4) NULL DEFAULT NULL,
`VALIDITY_DATE` date NULL DEFAULT NULL,
`MED_MADETIME` date NULL DEFAULT NULL,
`BATCHNO` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_PM_EXPORTINFO` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_pm_import` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`SEND_DEPT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`RECEIVE_DEPT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`PAKAGE_OUT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_BY` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`CREATE_DATE` date NULL DEFAULT NULL,
`IMPORT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_PM_IMPORT` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_pm_importinfo` (
`IMPORT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`MEDINFO_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_SPC` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_UNIT` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_AMOUNT` decimal(12,4) NULL DEFAULT NULL,
`MED_PRICE` decimal(12,4) NULL DEFAULT NULL,
`PURCHASE_PRICE` decimal(12,4) NULL DEFAULT NULL,
`WHOLESALE_PRICE` decimal(12,4) NULL DEFAULT NULL,
`VALIDITY_DATE` date NULL DEFAULT NULL,
`BATCHNO` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_MADETIME` date NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_PM_IMPORTINFO` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `his_pm_stock` (
`ID` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
`MEDINFO_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_SPC` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_UNIT` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`MED_AMOUNT` decimal(12,4) NULL DEFAULT NULL,
`MED_PRICE` decimal(12,4) NULL DEFAULT NULL,
`PURCHASE_PRICE` decimal(12,4) NULL DEFAULT NULL,
`WHOLESALE_PRICE` decimal(12,4) NULL DEFAULT NULL,
`VALIDITY_DATE` date NULL DEFAULT NULL,
`MED_MADETIME` date NULL DEFAULT NULL,
`BATCHNO` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
`DEPT_CODE` varchar(18) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `XPKHIS_PM_STOCK` (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;

