
CREATE TABLE HIS_BIL_CL_RECEIPT
(
	CL_RECEIPT_CODE      NVARCHAR(18) NOT NULL ,
	CL_CODE              NVARCHAR(18) NOT NULL ,
	CASHIER              NVARCHAR(18) NOT NULL ,
	RECEICPT_CODE        NVARCHAR(128) NOT NULL ,
	RECIVER_TIME         DATE NOT NULL ,
	CASH_AMT             FLOAT(10,2) NOT NULL ,
	CARD_AMT             FLOAT(10,2) NOT NULL ,
	INSURANCE_AMT        FLOAT(10,2) NULL ,
	SUM_AMT              FLOAT(10,2) NULL ,
	REFUND_RECP_CODE     NVARCHAR(128) NULL ,
	REFUND_DATE          DATE NULL ,
	REFUND_OPT           NVARCHAR(18) NULL ,
	REDUCE_AMT           INTEGER NULL ,
	REDUCE_DATE          DATE NULL ,
	REDUCE_OPT           NVARCHAR(18) NULL ,
	REDUCE_REASON        NVARCHAR(128) NULL ,
	OPT_USER             NVARCHAR(128) NOT NULL ,
	OPT_DATE             DATE NOT NULL ,
	OPT_TERM             NVARCHAR(128) NOT NULL ,
	OPT_ORGA             NVARCHAR(128) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_BIL_CL_RECEIPT ON HIS_BIL_CL_RECEIPT
(CL_RECEIPT_CODE   ASC,CL_CODE   ASC);



ALTER TABLE HIS_BIL_CL_RECEIPT
	ADD CONSTRAINT  XPKHIS_BIL_CL_RECEIPT PRIMARY KEY (CL_RECEIPT_CODE,CL_CODE);



CREATE TABLE HIS_BIL_CL_RECP_DETAIL
(
	ID                   NVARCHAR(18) NOT NULL ,
	CL_RECEIPT_CODE      NVARCHAR(18) NOT NULL ,
	CL_CODE              NVARCHAR(18) NOT NULL ,
	OPT_USER             NVARCHAR(128) NOT NULL ,
	OPT_DATE             DATE NOT NULL ,
	OPT_TERM             NVARCHAR(128) NOT NULL ,
	OPT_ORGA             NVARCHAR(128) NOT NULL ,
	FEEITEM_CODE         NVARCHAR(18) NOT NULL ,
	FEEITEM_NAME         NVARCHAR(18) NOT NULL ,
	PRICE                FLOAT(10,4) NOT NULL ,
	COUNT                FLOAT(10,2) NULL ,
	UNIT                 NVARCHAR(128) NULL ,
	AMT                  FLOAT(10,2) NULL 
);



CREATE UNIQUE INDEX XPKHIS_BIL_CL_RECP_DETAIL ON HIS_BIL_CL_RECP_DETAIL
(ID   ASC,CL_RECEIPT_CODE   ASC,CL_CODE   ASC);



ALTER TABLE HIS_BIL_CL_RECP_DETAIL
	ADD CONSTRAINT  XPKHIS_BIL_CL_RECP_DETAIL PRIMARY KEY (ID,CL_RECEIPT_CODE,CL_CODE);



CREATE TABLE HIS_BIL_COUNTER
(
	ID                   NVARCHAR(18) NOT NULL ,
	CASHIER              NVARCHAR(128) NOT NULL ,
	START_IVNNO          NVARCHAR(20) NOT NULL ,
	END_IVNNO            NVARCHAR(20) NOT NULL ,
	RECP_TYPE            NVARCHAR(20) NULL ,
	USE_TYPE             NVARCHAR(2) NOT NULL ,
	RECP_COUNT           FLOAT(5,0) NOT NULL ,
	PRE_CODE             NVARCHAR(20) NULL ,
	REFOUNDED_COUNT      FLOAT(5,0) NOT NULL ,
	INVALID_COUNT        FLOAT(5,0) NOT NULL ,
	OPT_USER             NVARCHAR(128) NOT NULL ,
	OPT_DATE             DATE NOT NULL ,
	OPT_TERM             NVARCHAR(128) NOT NULL ,
	OPT_ORGA             NVARCHAR(128) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_BIL_COUNTER ON HIS_BIL_COUNTER
(ID   ASC);



ALTER TABLE HIS_BIL_COUNTER
	ADD CONSTRAINT  XPKHIS_BIL_COUNTER PRIMARY KEY (ID);



CREATE TABLE HIS_CL_DAILY_STATEMENT
(
	ID                   NVARCHAR(18) NOT NULL ,
	OPERATOR             NVARCHAR(18) NULL ,
	OPERATE_TIME         DATE NULL ,
	RECIVER              NVARCHAR(18) NULL ,
	START_TIME           DATE NULL ,
	END_TIME             DATE NULL ,
	START_RECEIPT_CODE   NVARCHAR(18) NULL ,
	END_RECEIPT_CODE     NVARCHAR(18) NULL ,
	RECEIPT__NUM         NVARCHAR(18) NULL ,
	RETUEN_RECEIPT_NUM   NVARCHAR(18) NULL 
);



CREATE UNIQUE INDEX XPKHIS_CL_DAILY_STATEMENT ON HIS_CL_DAILY_STATEMENT
(ID   ASC);



ALTER TABLE HIS_CL_DAILY_STATEMENT
	ADD CONSTRAINT  XPKHIS_CL_DAILY_STATEMENT PRIMARY KEY (ID);



CREATE TABLE HIS_CL_DAILY_STATEMENT_ITEMTYP
(
	ID                   NVARCHAR(18) NOT NULL ,
	DAILY_CODE           NVARCHAR(18) NOT NULL ,
	ITEM_TYPE            NVARCHAR(20) NULL ,
	ITEM_SUM_PAY         INTEGER NULL ,
	ITEM_CASH_PAY        INTEGER NULL ,
	ITEM_CARD_PAY        INTEGER NULL ,
	ITEM_INSURANCE_PAY   INTEGER NULL ,
	STATUS               NVARCHAR(20) NULL 
);



CREATE UNIQUE INDEX XPKHIS_CL_DAILY_STATEMENT_ITEM ON HIS_CL_DAILY_STATEMENT_ITEMTYP
(ID   ASC,DAILY_CODE   ASC);



ALTER TABLE HIS_CL_DAILY_STATEMENT_ITEMTYP
	ADD CONSTRAINT  XPKHIS_CL_DAILY_STATEMENT_ITEM PRIMARY KEY (ID,DAILY_CODE);



CREATE TABLE HIS_CL_MEDICAL_RECORD
(
	CL_CODE              NVARCHAR(18) NOT NULL ,
	PHA_CODE             NVARCHAR(18) NOT NULL ,
	DOCTOR_CODE          NVARCHAR(18) NULL ,
	CL_DATE              DATE NULL ,
	IP                   NVARCHAR(18) NULL ,
	ICD_CODE             NVARCHAR(128) NULL ,
	ICD_NAME             NVARCHAR(128) NULL ,
	MEMO                 NVARCHAR(128) NULL ,
	OPT_USER             NVARCHAR(128) NOT NULL ,
	OPT_DATE             DATE NOT NULL ,
	OPT_TERM             NVARCHAR(128) NOT NULL ,
	OPT_ORGA             NVARCHAR(128) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_CL_MEDICAL_RECORD ON HIS_CL_MEDICAL_RECORD
(CL_CODE   ASC);



ALTER TABLE HIS_CL_MEDICAL_RECORD
	ADD CONSTRAINT  XPKHIS_CL_MEDICAL_RECORD PRIMARY KEY (CL_CODE);



CREATE TABLE HIS_CL_ORDER_ITEM
(
	ID                   NVARCHAR(18) NOT NULL ,
	CL_PRES_CODE         NVARCHAR(18) NOT NULL ,
	CL_CODE              NVARCHAR(18) NOT NULL ,
	ITEM_CODE            NVARCHAR(18) NULL ,
	ITEM_NAME            NVARCHAR(128) NULL ,
	COUNT                FLOAT(10,4) NULL ,
	PRICE                FLOAT(10,4) NULL ,
	ITEM_TYPE            NVARCHAR(1) NULL ,
	SPEC                 NVARCHAR(128) NULL ,
	UNIT                 NVARCHAR(128) NULL ,
	SUM_AMT              FLOAT(10,2) NULL ,
	STATUS               NVARCHAR(1) NULL ,
	HERB_NUM             FLOAT(10,4) NULL ,
	OPT_USER             NVARCHAR(128) NOT NULL ,
	OPT_DATE             DATE NOT NULL ,
	OPT_TERM             NVARCHAR(128) NOT NULL ,
	OPT_ORGA             NVARCHAR(128) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_CL_ORDER_ITEM ON HIS_CL_ORDER_ITEM
(ID   ASC,CL_PRES_CODE   ASC,CL_CODE   ASC);



ALTER TABLE HIS_CL_ORDER_ITEM
	ADD CONSTRAINT  XPKHIS_CL_ORDER_ITEM PRIMARY KEY (ID,CL_PRES_CODE,CL_CODE);



CREATE TABLE HIS_CL_PRES_DETAIL_CANCLE
(
	ID                   NVARCHAR(18) NOT NULL ,
	CL_PRES_CODE         NVARCHAR(18) NOT NULL ,
	CL_CODE              NVARCHAR(18) NOT NULL ,
	STATUS               NVARCHAR(2) NULL ,
	APPLY_DEPT_CODE      NVARCHAR(18) NULL ,
	DOCTOR_CODE          NVARCHAR(18) NULL ,
	OPERATE_DEPT_CODE    NVARCHAR(18) NULL ,
	SUM_AMT              FLOAT(10,2) NULL ,
	OPT_USER             NVARCHAR(128) NOT NULL ,
	OPT_DATE             DATE NOT NULL ,
	OPT_TERM             NVARCHAR(128) NOT NULL ,
	OPT_ORGA             NVARCHAR(128) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_CL_PRES_DETAIL_CANCLE ON HIS_CL_PRES_DETAIL_CANCLE
(ID   ASC,CL_PRES_CODE   ASC,CL_CODE   ASC);



ALTER TABLE HIS_CL_PRES_DETAIL_CANCLE
	ADD CONSTRAINT  XPKHIS_CL_PRES_DETAIL_CANCLE PRIMARY KEY (ID,CL_PRES_CODE,CL_CODE);



CREATE TABLE HIS_CL_PRESCRIPTION
(
	CL_PRES_CODE         NVARCHAR(18) NOT NULL ,
	CL_CODE              NVARCHAR(18) NOT NULL ,
	STATUS               NVARCHAR(1) NULL ,
	APPLY_DEPT_CODE      NVARCHAR(18) NULL ,
	DOCTOR_CODE          NVARCHAR(18) NULL ,
	OPERATE_DEPT_CODE    NVARCHAR(18) NULL ,
	SUM_AMT              FLOAT(10,2) NULL ,
	OPT_USER             NVARCHAR(128) NOT NULL ,
	OPT_DATE             DATE NOT NULL ,
	OPT_TERM             NVARCHAR(128) NOT NULL ,
	OPT_ORGA             NVARCHAR(128) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_CL_PRESCRIPTION ON HIS_CL_PRESCRIPTION
(CL_PRES_CODE   ASC,CL_CODE   ASC);



ALTER TABLE HIS_CL_PRESCRIPTION
	ADD CONSTRAINT  XPKHIS_CL_PRESCRIPTION PRIMARY KEY (CL_PRES_CODE,CL_CODE);



CREATE TABLE HIS_HOS_ACCOUNT
(
	HOS_ACC_CODE         NVARCHAR(18) NOT NULL ,
	HIS_HOS_CODE         NVARCHAR(18) NOT NULL ,
	IP                   NVARCHAR(18) NOT NULL ,
	SUM_IN               FLOAT(10,2) NOT NULL ,
	SUM_OUT              FLOAT(10,2) NOT NULL ,
	ACCOUNT_BALANCE      FLOAT(10,2) NULL ,
	LOWER_LIMIT          FLOAT(10,2) NULL ,
	OPT_USER             NVARCHAR(128) NOT NULL ,
	OPT_DATE             DATE NOT NULL ,
	OPT_TERM             NVARCHAR(128) NOT NULL ,
	OPT_ORGA             NVARCHAR(128) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_HOS_ACCOUNT ON HIS_HOS_ACCOUNT
(HOS_ACC_CODE   ASC,HIS_HOS_CODE   ASC);



ALTER TABLE HIS_HOS_ACCOUNT
	ADD CONSTRAINT  XPKHIS_HOS_ACCOUNT PRIMARY KEY (HOS_ACC_CODE,HIS_HOS_CODE);



CREATE TABLE HIS_HOS_ACCOUNT_LOG
(
	ID                   NVARCHAR(18) NOT NULL ,
	HOS_ACC_CODE         NVARCHAR(18) NOT NULL ,
	HIS_HOS_CODE         NVARCHAR(18) NOT NULL ,
	AMT                  FLOAT(12,2) NULL ,
	PAY_TYPE             NVARCHAR(1) NULL ,
	IS_REFUND            NVARCHAR(1) NULL ,
	OPT_USER             NVARCHAR(128) NOT NULL ,
	OPT_DATE             DATE NOT NULL ,
	OPT_TERM             NVARCHAR(128) NOT NULL ,
	OPT_ORGA             NVARCHAR(128) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_HOS_ACCOUNT_LOG ON HIS_HOS_ACCOUNT_LOG
(ID   ASC,HOS_ACC_CODE   ASC,HIS_HOS_CODE   ASC);



ALTER TABLE HIS_HOS_ACCOUNT_LOG
	ADD CONSTRAINT  XPKHIS_HOS_ACCOUNT_LOG PRIMARY KEY (ID,HOS_ACC_CODE,HIS_HOS_CODE);



CREATE TABLE HIS_HOS_DAILY_STATEMENT
(
	OPERATOR             NVARCHAR(18) NULL ,
	OPERATE_TIME         DATE NULL ,
	RECIVER              NVARCHAR(18) NULL ,
	START_TIME           DATE NULL ,
	END_TIME             DATE NULL ,
	START_RECEIPT_CODE   NVARCHAR(18) NULL ,
	END_RECEIPT_CODE     NVARCHAR(18) NULL ,
	RECEIPT__NUM         NVARCHAR(18) NULL ,
	RETUEN_RECEIPT_NUM   NVARCHAR(18) NULL ,
	ID                   NVARCHAR(18) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_HOS_DAILY_STATEMENT ON HIS_HOS_DAILY_STATEMENT
(ID   ASC);



ALTER TABLE HIS_HOS_DAILY_STATEMENT
	ADD CONSTRAINT  XPKHIS_HOS_DAILY_STATEMENT PRIMARY KEY (ID);



CREATE TABLE HIS_HOS_DAILY_STATEMENT_ITEMTY
(
	ID                   NVARCHAR(18) NOT NULL ,
	ITEM_TYPE            NVARCHAR(20) NULL ,
	ITEM_SUM_PAY         INTEGER NULL ,
	ITEM_CASH_PAY        INTEGER NULL ,
	ITEM_CARD_PAY        INTEGER NULL ,
	ITEM_INSURANCE_PAY   INTEGER NULL ,
	STATUS               NVARCHAR(20) NULL ,
	DAILY_CODE           NVARCHAR(18) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_HOS_DAILY_STATEMENT_ITE ON HIS_HOS_DAILY_STATEMENT_ITEMTY
(ID   ASC,DAILY_CODE   ASC);



ALTER TABLE HIS_HOS_DAILY_STATEMENT_ITEMTY
	ADD CONSTRAINT  XPKHIS_HOS_DAILY_STATEMENT_ITE PRIMARY KEY (ID,DAILY_CODE);



CREATE TABLE HIS_HOS_MEDICAL_RECORD
(
	IP                   NVARCHAR(18) NULL ,
	HIS_HOS_CODE         NVARCHAR(18) NOT NULL ,
	Case_Code            NVARCHAR(18) NULL ,
	Patient_Name         NVARCHAR(18) NULL ,
	MD_Dept_ID           FLOAT(18) NULL ,
	MD_SickRoom_ID       FLOAT(18) NULL ,
	ME_Bed_ID            FLOAT(1) NULL ,
	In_Date              DATE NULL ,
	Out_Date             DATE NULL ,
	Status               FLOAT(1) NULL ,
	In_Hospital_Order    FLOAT(2) NULL ,
	Create_by            NVARCHAR(18) NULL ,
	Update_date          DATE NULL ,
	Update_by            NVARCHAR(18) NULL ,
	is_removed           FLOAT(1) NULL ,
	Help_Code            NVARCHAR(18) NULL ,
	Create_date          DATE NULL ,
	Charge_Doctor_Name   NVARCHAR(18) NULL ,
	Charge_Nurse_ID      FLOAT(18) NULL ,
	Charge_Nurse_Name    NVARCHAR(18) NULL ,
	Patient_Pay_Type     NVARCHAR(18) NULL ,
	NURSING_CLASS        NVARCHAR(128) NULL ,
	PATIENT_CONDITION    NVARCHAR(128) NULL ,
	ACCL_ACCT_ID         INTEGER NULL ,
	TYPE                 NVARCHAR(10) NULL ,
	CHANGE_DEPT_HELP     NVARCHAR(512) NULL ,
	IN_WAY               NVARCHAR(64) NULL ,
	IN_WAY_Doctor        NVARCHAR(64) NULL ,
	IS_INFECTION         FLOAT(2) NULL ,
	INTRODUCER           NVARCHAR(64) NULL ,
	ATTENDING_DOCTOR_ID  INTEGER NULL ,
	IN_HOS_AGE           NVARCHAR(32) NULL ,
	MD_DEPT_NAME         NVARCHAR(128) NULL ,
	MD_BED_CODE          NVARCHAR(128) NULL ,
	MD_SICKROOM_NAME     NVARCHAR(128) NULL ,
	DOC_EDIT_IS          INTEGER NULL ,
	DOC_EDIT_Account     NVARCHAR(128) NULL ,
	Nurse_EDIT_IS        INTEGER NULL ,
	Nurse_EDITAccount    NVARCHAR(128) NULL 
);



CREATE UNIQUE INDEX XPKHIS_HOS_MEDICAL_RECORD ON HIS_HOS_MEDICAL_RECORD
(HIS_HOS_CODE   ASC);



ALTER TABLE HIS_HOS_MEDICAL_RECORD
	ADD CONSTRAINT  XPKHIS_HOS_MEDICAL_RECORD PRIMARY KEY (HIS_HOS_CODE);



CREATE TABLE HIS_HOS_MONTHLY_STATEMENT
(
	OPERATOR             NVARCHAR(18) NULL ,
	OPERATE_TIME         DATE NULL ,
	RECIVER              NVARCHAR(18) NULL ,
	START_TIME           DATE NULL ,
	END_TIME             DATE NULL ,
	START_RECEIPT_CODE   NVARCHAR(18) NULL ,
	END_RECEIPT_CODE     NVARCHAR(18) NULL ,
	RECEIPT__NUM         NVARCHAR(18) NULL ,
	RETUEN_RECEIPT_NUM   NVARCHAR(18) NULL ,
	ID                   NVARCHAR(18) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_HOS_MONTHLY_STATEMENT ON HIS_HOS_MONTHLY_STATEMENT
(ID   ASC);



ALTER TABLE HIS_HOS_MONTHLY_STATEMENT
	ADD CONSTRAINT  XPKHIS_HOS_MONTHLY_STATEMENT PRIMARY KEY (ID);



CREATE TABLE HIS_HOS_MONTHLY_STATEMENT_ITEM
(
	ITEM_TYPE            NVARCHAR(20) NULL ,
	ITEM_SUM_PAY         INTEGER NULL ,
	ITEM_CASH_PAY        INTEGER NULL ,
	ITEM_CARD_PAY        INTEGER NULL ,
	ITEM_INSURANCE_PAY   INTEGER NULL ,
	STATUS               NVARCHAR(20) NULL ,
	ID                   NVARCHAR(18) NOT NULL ,
	MONTHLY_CODE         NVARCHAR(18) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_HOS_MONTHLY_STATEMENT_I ON HIS_HOS_MONTHLY_STATEMENT_ITEM
(ID   ASC,MONTHLY_CODE   ASC);



ALTER TABLE HIS_HOS_MONTHLY_STATEMENT_ITEM
	ADD CONSTRAINT  XPKHIS_HOS_MONTHLY_STATEMENT_I PRIMARY KEY (ID,MONTHLY_CODE);



CREATE TABLE HIS_HOS_ORDER_ITEM
(
	ID                   NVARCHAR(18) NOT NULL ,
	HOS_PRES_CODE        NVARCHAR(18) NOT NULL ,
	HIS_HOS_CODE         NVARCHAR(18) NOT NULL ,
	ITEM_CODE            NVARCHAR(18) NULL ,
	ITEM_NAME            NVARCHAR(128) NULL ,
	COUNT                FLOAT(10,4) NULL ,
	PRICE                FLOAT(10,4) NULL ,
	ITEM_TYPE            NVARCHAR(1) NULL ,
	SPEC                 NVARCHAR(128) NULL ,
	UNIT                 NVARCHAR(128) NULL ,
	SUM_AMT              FLOAT(10,2) NULL ,
	STATUS               NVARCHAR(1) NULL ,
	HERB_NUM             FLOAT(10,4) NULL ,
	OPT_USER             NVARCHAR(128) NOT NULL ,
	OPT_DATE             DATE NOT NULL ,
	OPT_TERM             NVARCHAR(128) NOT NULL ,
	OPT_ORGA             NVARCHAR(128) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_HOS_ORDER_ITEM ON HIS_HOS_ORDER_ITEM
(ID   ASC,HOS_PRES_CODE   ASC,HIS_HOS_CODE   ASC);



ALTER TABLE HIS_HOS_ORDER_ITEM
	ADD CONSTRAINT  XPKHIS_HOS_ORDER_ITEM PRIMARY KEY (ID,HOS_PRES_CODE,HIS_HOS_CODE);



CREATE TABLE HIS_HOS_PRES_DETAIL_CANCLE
(
	ID                   NVARCHAR(18) NOT NULL ,
	STATUS               NVARCHAR(2) NULL ,
	APPLY_DEPT_CODE      NVARCHAR(18) NULL ,
	DOCTOR_CODE          NVARCHAR(18) NULL ,
	OPERATE_DEPT_CODE    NVARCHAR(18) NULL ,
	SUM_AMT              FLOAT(10,2) NULL ,
	OPT_USER             NVARCHAR(128) NOT NULL ,
	OPT_DATE             DATE NOT NULL ,
	OPT_TERM             NVARCHAR(128) NOT NULL ,
	OPT_ORGA             NVARCHAR(128) NOT NULL ,
	HOS_PRES_CODE        NVARCHAR(18) NOT NULL ,
	HIS_HOS_CODE         NVARCHAR(18) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_HOS_PRES_DETAIL_CANCLE ON HIS_HOS_PRES_DETAIL_CANCLE
(ID   ASC,HOS_PRES_CODE   ASC,HIS_HOS_CODE   ASC);



ALTER TABLE HIS_HOS_PRES_DETAIL_CANCLE
	ADD CONSTRAINT  XPKHIS_HOS_PRES_DETAIL_CANCLE PRIMARY KEY (ID,HOS_PRES_CODE,HIS_HOS_CODE);



CREATE TABLE HIS_HOS_PRESCRIPTION
(
	HOS_PRES_CODE        NVARCHAR(18) NOT NULL ,
	HIS_HOS_CODE         NVARCHAR(18) NOT NULL ,
	STATUS               NVARCHAR(1) NULL ,
	APPLY_DEPT_CODE      NVARCHAR(18) NULL ,
	DOCTOR_CODE          NVARCHAR(18) NULL ,
	OPERATE_DEPT_CODE    NVARCHAR(18) NULL ,
	SUM_AMT              FLOAT(10,2) NULL ,
	OPT_USER             NVARCHAR(128) NOT NULL ,
	OPT_DATE             DATE NOT NULL ,
	OPT_TERM             NVARCHAR(128) NOT NULL ,
	OPT_ORGA             NVARCHAR(128) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_HOS_PRESCRIPTION ON HIS_HOS_PRESCRIPTION
(HOS_PRES_CODE   ASC,HIS_HOS_CODE   ASC);



ALTER TABLE HIS_HOS_PRESCRIPTION
	ADD CONSTRAINT  XPKHIS_HOS_PRESCRIPTION PRIMARY KEY (HOS_PRES_CODE,HIS_HOS_CODE);



CREATE TABLE HIS_HOS_RECEIPT
(
	HOS_RECEIPT_CODE     NVARCHAR(18) NOT NULL ,
	HIS_HOS_CODE         NVARCHAR(18) NOT NULL ,
	CASHIER              NVARCHAR(18) NOT NULL ,
	RECEICPT_CODE        NVARCHAR(128) NOT NULL ,
	RECIVER_TIME         DATE NOT NULL ,
	CASH_AMT             FLOAT(10,2) NOT NULL ,
	CARD_AMT             FLOAT(10,2) NOT NULL ,
	INSURANCE_AMT        FLOAT(10,2) NULL ,
	SUM_AMT              FLOAT(10,2) NULL ,
	REDUCE_AMT           INTEGER NULL ,
	REDUCE_DATE          DATE NULL ,
	REDUCE_OPT           NVARCHAR(18) NULL ,
	REDUCE_REASON        NVARCHAR(128) NULL ,
	OPT_USER             NVARCHAR(128) NOT NULL ,
	OPT_DATE             DATE NOT NULL ,
	OPT_TERM             NVARCHAR(128) NOT NULL ,
	OPT_ORGA             NVARCHAR(128) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_HOS_RECEIPT ON HIS_HOS_RECEIPT
(HOS_RECEIPT_CODE   ASC,HIS_HOS_CODE   ASC);



ALTER TABLE HIS_HOS_RECEIPT
	ADD CONSTRAINT  XPKHIS_HOS_RECEIPT PRIMARY KEY (HOS_RECEIPT_CODE,HIS_HOS_CODE);



CREATE TABLE HIS_HOS_RECEIPT_CANCLE
(
	HOS_RECEIPT_CODE     NVARCHAR(18) NOT NULL ,
	HIS_HOS_CODE         NVARCHAR(18) NOT NULL ,
	CASHIER              NVARCHAR(18) NOT NULL ,
	RECEICPT_CODE        NVARCHAR(128) NOT NULL ,
	RECIVER_TIME         DATE NOT NULL ,
	CASH_AMT             FLOAT(10,2) NOT NULL ,
	CARD_AMT             FLOAT(10,2) NOT NULL ,
	INSURANCE_AMT        FLOAT(10,2) NULL ,
	SUM_AMT              FLOAT(10,2) NULL ,
	REDUCE_AMT           INTEGER NULL ,
	REDUCE_DATE          DATE NULL ,
	REDUCE_OPT           NVARCHAR(18) NULL ,
	REDUCE_REASON        NVARCHAR(128) NULL ,
	OPT_USER             NVARCHAR(128) NOT NULL ,
	OPT_DATE             DATE NOT NULL ,
	OPT_TERM             NVARCHAR(128) NOT NULL ,
	OPT_ORGA             NVARCHAR(128) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_HOS_RECEIPT_CANCLE ON HIS_HOS_RECEIPT_CANCLE
(HOS_RECEIPT_CODE   ASC,HIS_HOS_CODE   ASC);



ALTER TABLE HIS_HOS_RECEIPT_CANCLE
	ADD CONSTRAINT  XPKHIS_HOS_RECEIPT_CANCLE PRIMARY KEY (HOS_RECEIPT_CODE,HIS_HOS_CODE);



CREATE TABLE HIS_HOS_RECEIPT_DETAIL
(
	ID                   NVARCHAR(18) NOT NULL ,
	HOS_RECEIPT_CODE     NVARCHAR(18) NOT NULL ,
	HIS_HOS_CODE         NVARCHAR(18) NOT NULL ,
	FEEITEM_CODE         NVARCHAR(18) NOT NULL ,
	FEEITEM_NAME         NVARCHAR(18) NOT NULL ,
	PRICE                FLOAT(10,4) NOT NULL ,
	COUNT                FLOAT(10,2) NULL ,
	UNIT                 NVARCHAR(128) NULL ,
	AMT                  FLOAT(10,2) NULL ,
	OPT_USER             NVARCHAR(128) NOT NULL ,
	OPT_DATE             DATE NOT NULL ,
	OPT_TERM             NVARCHAR(128) NOT NULL ,
	OPT_ORGA             NVARCHAR(128) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_HOS_RECEIPT_DETAIL ON HIS_HOS_RECEIPT_DETAIL
(ID   ASC,HOS_RECEIPT_CODE   ASC,HIS_HOS_CODE   ASC);



ALTER TABLE HIS_HOS_RECEIPT_DETAIL
	ADD CONSTRAINT  XPKHIS_HOS_RECEIPT_DETAIL PRIMARY KEY (ID,HOS_RECEIPT_CODE,HIS_HOS_CODE);



CREATE TABLE HIS_HOS_RECEIPT_DETAIL_CANCLE
(
	ID                   NVARCHAR(18) NOT NULL ,
	HOS_RECEIPT_CODE     NVARCHAR(18) NOT NULL ,
	HIS_HOS_CODE         NVARCHAR(18) NOT NULL ,
	FEEITEM_CODE         NVARCHAR(18) NOT NULL ,
	FEEITEM_NAME         NVARCHAR(18) NOT NULL ,
	PRICE                FLOAT(10,4) NOT NULL ,
	COUNT                FLOAT(10,2) NULL ,
	UNIT                 NVARCHAR(128) NULL ,
	AMT                  FLOAT(10,2) NULL ,
	OPT_USER             NVARCHAR(128) NOT NULL ,
	OPT_DATE             DATE NOT NULL ,
	OPT_TERM             NVARCHAR(128) NOT NULL ,
	OPT_ORGA             NVARCHAR(128) NOT NULL 
);



CREATE UNIQUE INDEX XPKHIS_HOS_RECEIPT_DETAIL_CANC ON HIS_HOS_RECEIPT_DETAIL_CANCLE
(ID   ASC,HOS_RECEIPT_CODE   ASC,HIS_HOS_CODE   ASC);



ALTER TABLE HIS_HOS_RECEIPT_DETAIL_CANCLE
	ADD CONSTRAINT  XPKHIS_HOS_RECEIPT_DETAIL_CANC PRIMARY KEY (ID,HOS_RECEIPT_CODE,HIS_HOS_CODE);

commit;

